# Generated by Django 5.2.18 on 2026-10-06 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Usuario"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Creación"),
                            ("UPDATE", "Edición"),
                            ("VOID", "Anulación"),
                            ("PAYMENT", "Registro de pago"),
                            ("RATE_CHANGE", "Modificación de tasa"),
                            ("MATURITY_CHANGE", "Cambio de vencimiento"),
                            ("CAPITAL_CHANGE", "Cambio de capital"),
                            ("PENALTY_CHANGE", "Cambio de penalidad"),
                            ("STATUS_CHANGE", "Cambio de estado"),
                            ("LOGIN", "Inicio de sesión"),
                            ("LOGIN_FAILED", "Intento de acceso fallido"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("PASSWORD", "Cambio de contraseña"),
                            ("UPLOAD", "Carga de documento"),
                            ("DOWNLOAD", "Descarga de documento"),
                            ("EXPORT", "Exportación"),
                            ("PERMISSION", "Cambio de permisos"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="Módulo"
                    ),
                ),
                (
                    "record_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        verbose_name="ID del registro",
                    ),
                ),
                (
                    "record_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Registro afectado"
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Valor anterior"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="Valor nuevo"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="Detalle")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "db_table": "audit_logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
