# Generated by Django 5.2.18 on 2026-10-06 21:43

import core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Descripción"
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("TEA", "Tasa efectiva anual (TEA)"),
                            ("TNA", "Tasa nominal anual (TNA)"),
                            ("TEM", "Tasa efectiva mensual (TEM)"),
                            ("TNM", "Tasa nominal mensual (TNM)"),
                        ],
                        default="TNM",
                        max_length=3,
                        verbose_name="Tipo de tasa",
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("2.9"),
                        max_digits=9,
                        verbose_name="Tasa (%)",
                    ),
                ),
                (
                    "interest_method",
                    models.CharField(
                        choices=[
                            ("SIMPLE", "Interés simple"),
                            ("COMPOUND", "Interés compuesto"),
                        ],
                        default="SIMPLE",
                        max_length=8,
                        verbose_name="Método",
                    ),
                ),
                (
                    "day_base",
                    models.PositiveSmallIntegerField(
                        choices=[(360, "Base 360"), (365, "Base 365")],
                        default=360,
                        verbose_name="Base de días",
                    ),
                ),
                (
                    "day_count",
                    models.CharField(
                        choices=[
                            ("ACTUAL", "Días reales entre fechas (ACT)"),
                            ("PERIOD", "Periodo estándar (30 días por mes)"),
                        ],
                        default="ACTUAL",
                        max_length=6,
                        verbose_name="Conteo de días",
                    ),
                ),
                (
                    "capitalizations_per_year",
                    models.PositiveSmallIntegerField(
                        default=12,
                        verbose_name="Capitalizaciones por año (tasas nominales)",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Mensual"),
                            ("BIMONTHLY", "Bimestral"),
                            ("QUARTERLY", "Trimestral"),
                            ("SEMIANNUAL", "Semestral"),
                            ("ANNUAL", "Anual"),
                            ("AT_MATURITY", "Al vencimiento (pago único)"),
                        ],
                        default="MONTHLY",
                        max_length=12,
                        verbose_name="Periodicidad",
                    ),
                ),
                (
                    "amortization",
                    models.CharField(
                        choices=[
                            (
                                "BULLET",
                                "Bullet: solo intereses y capital al vencimiento",
                            ),
                            ("FRENCH", "Francés: cuota constante"),
                            ("GERMAN", "Alemán: amortización constante"),
                        ],
                        default="BULLET",
                        max_length=6,
                        verbose_name="Amortización",
                    ),
                ),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Sin penalidad"),
                            ("FIXED", "Monto fijo por cuota vencida"),
                            ("PERCENT", "Porcentaje único sobre lo vencido"),
                            ("DAILY_PERCENT", "Porcentaje diario sobre lo vencido"),
                            ("DAILY_FIXED", "Monto fijo por día de atraso"),
                            ("MORATORY", "Tasa moratoria anual (interés simple)"),
                        ],
                        default="DAILY_PERCENT",
                        max_length=14,
                        verbose_name="Tipo de penalidad",
                    ),
                ),
                (
                    "penalty_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1"),
                        max_digits=12,
                        verbose_name="Valor de penalidad",
                    ),
                ),
                (
                    "penalty_base",
                    models.CharField(
                        choices=[
                            ("INSTALLMENT", "Cuota vencida (capital + interés)"),
                            ("CAPITAL", "Capital vencido"),
                            ("INTEREST", "Interés vencido"),
                        ],
                        default="INSTALLMENT",
                        max_length=12,
                        verbose_name="Base de penalidad",
                    ),
                ),
                (
                    "penalty_grace_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Días de tolerancia"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "db_table": "financial_profiles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="CAPEX Express S.A.C.",
                        max_length=150,
                        verbose_name="Nombre de la empresa",
                    ),
                ),
                (
                    "company_ruc",
                    models.CharField(blank=True, max_length=20, verbose_name="RUC"),
                ),
                (
                    "company_address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Dirección"
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        blank=True, upload_to="branding/", verbose_name="Logo"
                    ),
                ),
                (
                    "default_currency",
                    models.CharField(
                        choices=[("PEN", "Soles (PEN)"), ("USD", "Dólares (USD)")],
                        default="USD",
                        max_length=3,
                        verbose_name="Moneda por defecto",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("3.7500"),
                        max_digits=8,
                        verbose_name="Tipo de cambio referencial (S/ por US$)",
                    ),
                ),
                (
                    "max_ltv",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        max_digits=5,
                        verbose_name="Límite máximo de LTV (%)",
                    ),
                ),
                (
                    "alert_days",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="Días de alerta para cuotas por vencer"
                    ),
                ),
                (
                    "maturity_alert_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        verbose_name="Días de alerta para operaciones por vencer",
                    ),
                ),
                (
                    "mora_days",
                    models.PositiveSmallIntegerField(
                        default=30,
                        verbose_name="Días de atraso para considerar EN MORA",
                    ),
                ),
                (
                    "appraisal_validity_months",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Vigencia de tasación (meses)"
                    ),
                ),
                (
                    "allocation_order",
                    models.CharField(
                        choices=[
                            (
                                "PENALTY,INTEREST,CAPITAL",
                                "Penalidad → interés → capital",
                            ),
                            (
                                "INTEREST,PENALTY,CAPITAL",
                                "Interés → penalidad → capital",
                            ),
                            (
                                "INTEREST,CAPITAL,PENALTY",
                                "Interés → capital → penalidad",
                            ),
                        ],
                        default="PENALTY,INTEREST,CAPITAL",
                        max_length=40,
                        verbose_name="Orden de aplicación de pagos",
                    ),
                ),
                (
                    "required_documents",
                    models.CharField(
                        default="CONTRATO,TASACION,COPIA_LITERAL,CONTRATO_FIDEICOMISO",
                        help_text="Códigos separados por coma.",
                        max_length=300,
                        verbose_name="Documentos obligatorios por operación",
                    ),
                ),
                (
                    "operation_prefix",
                    models.CharField(
                        default="OP",
                        max_length=5,
                        verbose_name="Prefijo de operaciones",
                    ),
                ),
                (
                    "last_refresh",
                    models.DateField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "db_table": "system_settings",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Código del cliente",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=200,
                        verbose_name="Nombres y apellidos o razón social",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CE", "Carné de extranjería"),
                            ("RUC", "RUC"),
                            ("PAS", "Pasaporte"),
                        ],
                        default="DNI",
                        max_length=3,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° de documento"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Dirección"
                    ),
                ),
                (
                    "economic_activity",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Actividad económica"
                    ),
                ),
                (
                    "declared_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Ingresos declarados (mensual)",
                    ),
                ),
                (
                    "income_currency",
                    models.CharField(
                        choices=[("PEN", "Soles (PEN)"), ("USD", "Dólares (USD)")],
                        default="PEN",
                        max_length=3,
                        verbose_name="Moneda de ingresos",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("OBSERVADO", "Observado"),
                        ],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asesor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clients",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="ID del bonista",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=120, verbose_name="Nombres o razón social"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Apellidos"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CE", "Carné de extranjería"),
                            ("RUC", "RUC"),
                            ("PAS", "Pasaporte"),
                        ],
                        default="DNI",
                        max_length=3,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="N° de documento"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Dirección"
                    ),
                ),
                (
                    "bank",
                    models.CharField(blank=True, max_length=80, verbose_name="Banco"),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="N° de cuenta"
                    ),
                ),
                (
                    "cci",
                    models.CharField(blank=True, max_length=30, verbose_name="CCI"),
                ),
                ("registered_on", models.DateField(verbose_name="Fecha de registro")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investors",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Capital entregado",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("PEN", "Soles (PEN)"), ("USD", "Dólares (USD)")],
                        default="USD",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "disbursement_date",
                    models.DateField(verbose_name="Fecha de desembolso"),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "maturity_date",
                    models.DateField(
                        editable=False, verbose_name="Fecha de vencimiento"
                    ),
                ),
                (
                    "term_months",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Plazo (meses)",
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("TEA", "Tasa efectiva anual (TEA)"),
                            ("TNA", "Tasa nominal anual (TNA)"),
                            ("TEM", "Tasa efectiva mensual (TEM)"),
                            ("TNM", "Tasa nominal mensual (TNM)"),
                        ],
                        max_length=3,
                        verbose_name="Tipo de tasa",
                    ),
                ),
                (
                    "rate_value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Tasa de interés (%)",
                    ),
                ),
                (
                    "interest_method",
                    models.CharField(
                        choices=[
                            ("SIMPLE", "Interés simple"),
                            ("COMPOUND", "Interés compuesto"),
                        ],
                        max_length=8,
                        verbose_name="Método de interés",
                    ),
                ),
                (
                    "day_base",
                    models.PositiveSmallIntegerField(
                        choices=[(360, "Base 360"), (365, "Base 365")],
                        verbose_name="Base de días",
                    ),
                ),
                (
                    "day_count",
                    models.CharField(
                        choices=[
                            ("ACTUAL", "Días reales entre fechas (ACT)"),
                            ("PERIOD", "Periodo estándar (30 días por mes)"),
                        ],
                        max_length=6,
                        verbose_name="Conteo de días",
                    ),
                ),
                (
                    "capitalizations_per_year",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Capitalizaciones por año"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Mensual"),
                            ("BIMONTHLY", "Bimestral"),
                            ("QUARTERLY", "Trimestral"),
                            ("SEMIANNUAL", "Semestral"),
                            ("ANNUAL", "Anual"),
                            ("AT_MATURITY", "Al vencimiento (pago único)"),
                        ],
                        max_length=12,
                        verbose_name="Periodicidad de pago",
                    ),
                ),
                (
                    "amortization",
                    models.CharField(
                        choices=[
                            (
                                "BULLET",
                                "Bullet: solo intereses y capital al vencimiento",
                            ),
                            ("FRENCH", "Francés: cuota constante"),
                            ("GERMAN", "Alemán: amortización constante"),
                        ],
                        max_length=6,
                        verbose_name="Amortización",
                    ),
                ),
                (
                    "payment_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Vacío: mismo día de la fecha de inicio.",
                        null=True,
                        verbose_name="Día de pago",
                    ),
                ),
                (
                    "grace_periods",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Periodos de gracia"
                    ),
                ),
                (
                    "grace_type",
                    models.CharField(
                        choices=[
                            ("PARTIAL", "Parcial: se pagan intereses"),
                            ("TOTAL", "Total: intereses se capitalizan"),
                        ],
                        default="PARTIAL",
                        max_length=7,
                        verbose_name="Tipo de gracia",
                    ),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=14,
                        verbose_name="Monto de cuota o interés",
                    ),
                ),
                (
                    "installments_count",
                    models.PositiveSmallIntegerField(
                        default=0, editable=False, verbose_name="Número de cuotas"
                    ),
                ),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Sin penalidad"),
                            ("FIXED", "Monto fijo por cuota vencida"),
                            ("PERCENT", "Porcentaje único sobre lo vencido"),
                            ("DAILY_PERCENT", "Porcentaje diario sobre lo vencido"),
                            ("DAILY_FIXED", "Monto fijo por día de atraso"),
                            ("MORATORY", "Tasa moratoria anual (interés simple)"),
                        ],
                        default="NONE",
                        max_length=14,
                        verbose_name="Tipo de penalidad",
                    ),
                ),
                (
                    "penalty_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Valor de penalidad",
                    ),
                ),
                (
                    "penalty_base",
                    models.CharField(
                        choices=[
                            ("INSTALLMENT", "Cuota vencida (capital + interés)"),
                            ("CAPITAL", "Capital vencido"),
                            ("INTEREST", "Interés vencido"),
                        ],
                        default="INSTALLMENT",
                        max_length=12,
                        verbose_name="Base de penalidad",
                    ),
                ),
                (
                    "penalty_grace_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Días de tolerancia"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("AL_DIA", "Al día"),
                            ("POR_VENCER", "Por vencer"),
                            ("VENCIDA", "Vencida"),
                            ("EN_MORA", "En mora"),
                            ("CANCELADA", "Cancelada"),
                            ("REESTRUCTURADA", "Reestructurada"),
                        ],
                        db_index=True,
                        default="ACTIVA",
                        max_length=15,
                        verbose_name="Estado",
                    ),
                ),
                ("closed_manually", models.BooleanField(default=False, editable=False)),
                (
                    "close_reason",
                    models.TextField(
                        blank=True, editable=False, verbose_name="Motivo de cierre"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Destino del crédito"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "capital_pending",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=14,
                    ),
                ),
                ("days_late", models.IntegerField(default=0, editable=False)),
                (
                    "next_due_date",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "refreshed_on",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "schedule_version",
                    models.PositiveSmallIntegerField(default=1, editable=False),
                ),
                (
                    "advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asesor",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="core.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="core.investor",
                        verbose_name="Bonista",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.financialprofile",
                        verbose_name="Perfil de condiciones",
                    ),
                ),
                (
                    "restructured_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="restructurings",
                        to="core.operation",
                        verbose_name="Reestructura de",
                    ),
                ),
            ],
            options={
                "db_table": "operations",
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="Fecha de pago")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("PEN", "Soles (PEN)"), ("USD", "Dólares (USD)")],
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "concept",
                    models.CharField(
                        choices=[
                            ("CUOTA", "Pago de cuota"),
                            ("PREPAGO", "Pago adelantado"),
                            ("CANCELACION", "Cancelación total"),
                            ("PENALIDAD", "Pago de penalidad"),
                            ("OTRO", "Otro"),
                        ],
                        default="CUOTA",
                        max_length=12,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "capital",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Capital",
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Interés",
                    ),
                ),
                (
                    "penalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Penalidad",
                    ),
                ),
                (
                    "bank_reference",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="N° de operación bancaria",
                    ),
                ),
                (
                    "bank",
                    models.CharField(blank=True, max_length=80, verbose_name="Banco"),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("TRANSFERENCIA", "Transferencia"),
                            ("DEPOSITO", "Depósito en cuenta"),
                            ("EFECTIVO", "Efectivo"),
                            ("CHEQUE", "Cheque"),
                            ("BILLETERA", "Yape / Plin"),
                            ("OTRO", "Otro"),
                        ],
                        default="TRANSFERENCIA",
                        max_length=14,
                        verbose_name="Medio de pago",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "status",
                    models.CharField(
                        choices=[("VALIDO", "Válido"), ("ANULADO", "Anulado")],
                        db_index=True,
                        default="VALIDO",
                        max_length=8,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.TextField(blank=True, verbose_name="Motivo de anulación"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.operation",
                        verbose_name="Operación",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-payment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("number", models.PositiveSmallIntegerField(verbose_name="N° cuota")),
                ("period_start", models.DateField(verbose_name="Inicio del periodo")),
                ("due_date", models.DateField(verbose_name="Fecha de vencimiento")),
                (
                    "days",
                    models.PositiveSmallIntegerField(verbose_name="Días del periodo"),
                ),
                (
                    "period_rate",
                    models.DecimalField(
                        decimal_places=10,
                        max_digits=14,
                        verbose_name="Tasa del periodo",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Saldo inicial"
                    ),
                ),
                (
                    "capital",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Capital"
                    ),
                ),
                (
                    "interest",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Interés"
                    ),
                ),
                (
                    "capitalized_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Interés capitalizado",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Saldo de capital"
                    ),
                ),
                (
                    "paid_capital",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "paid_interest",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "waived_interest",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Interés descontado por prepago",
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Penalidad",
                    ),
                ),
                (
                    "paid_penalty",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
                (
                    "days_late",
                    models.IntegerField(default=0, verbose_name="Días de atraso"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PAGADO", "Pagado"),
                            ("PAGO_PARCIAL", "Pago parcial"),
                            ("VENCIDO", "Vencido"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule",
                        to="core.operation",
                    ),
                ),
            ],
            options={
                "db_table": "payment_schedules",
                "ordering": ["operation", "version", "number"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("CAPITAL", "Capital"),
                            ("INTEREST", "Interés"),
                            ("PENALTY", "Penalidad"),
                            (
                                "INT_WAIVED",
                                "Interés no devengado (descuento por cancelación anticipada)",
                            ),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="core.payment",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="core.paymentschedule",
                    ),
                ),
            ],
            options={
                "db_table": "payment_allocations",
            },
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Sin penalidad"),
                            ("FIXED", "Monto fijo por cuota vencida"),
                            ("PERCENT", "Porcentaje único sobre lo vencido"),
                            ("DAILY_PERCENT", "Porcentaje diario sobre lo vencido"),
                            ("DAILY_FIXED", "Monto fijo por día de atraso"),
                            ("MORATORY", "Tasa moratoria anual (interés simple)"),
                        ],
                        max_length=14,
                        verbose_name="Tipo de penalidad",
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("INSTALLMENT", "Cuota vencida (capital + interés)"),
                            ("CAPITAL", "Capital vencido"),
                            ("INTEREST", "Interés vencido"),
                        ],
                        max_length=12,
                        verbose_name="Base de cálculo",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        verbose_name="Porcentaje o monto",
                    ),
                ),
                (
                    "grace_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Días de tolerancia"
                    ),
                ),
                ("day_base", models.PositiveSmallIntegerField(default=360)),
                ("applies_from", models.DateField(verbose_name="Se aplica desde")),
                (
                    "days_late",
                    models.IntegerField(default=0, verbose_name="Días de atraso"),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Penalidad calculada",
                    ),
                ),
                (
                    "waived_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Monto condonado",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Penalidad pagada",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VIGENTE", "Vigente"),
                            ("PAGADA", "Pagada"),
                            ("CONDONADA", "Condonada"),
                            ("SIN_EFECTO", "Sin efecto (recalculada a cero)"),
                        ],
                        default="VIGENTE",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "formula",
                    models.TextField(blank=True, verbose_name="Fórmula aplicada"),
                ),
                ("last_calculated", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "installment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penalty",
                        to="core.paymentschedule",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="penalties",
                        to="core.operation",
                    ),
                ),
            ],
            options={
                "db_table": "penalties",
                "ordering": ["-applies_from"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("CASA", "Casa"),
                            ("DEPARTAMENTO", "Departamento"),
                            ("TERRENO_URBANO", "Terreno urbano"),
                            ("TERRENO_RUSTICO", "Terreno rústico"),
                            ("LOCAL_COMERCIAL", "Local comercial"),
                            ("OFICINA", "Oficina"),
                            ("INDUSTRIAL", "Inmueble industrial"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=16,
                        verbose_name="Tipo de inmueble",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=200, verbose_name="Propietario"),
                ),
                (
                    "owner_doc",
                    models.CharField(max_length=20, verbose_name="DNI/RUC propietario"),
                ),
                ("address", models.CharField(max_length=250, verbose_name="Dirección")),
                ("district", models.CharField(max_length=80, verbose_name="Distrito")),
                ("province", models.CharField(max_length=80, verbose_name="Provincia")),
                (
                    "department",
                    models.CharField(max_length=80, verbose_name="Departamento"),
                ),
                (
                    "registry_number",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        verbose_name="Partida registral SUNARP",
                    ),
                ),
                (
                    "registry_office",
                    models.CharField(max_length=80, verbose_name="Oficina registral"),
                ),
                (
                    "value_currency",
                    models.CharField(
                        choices=[("PEN", "Soles (PEN)"), ("USD", "Dólares (USD)")],
                        default="USD",
                        max_length=3,
                        verbose_name="Moneda de valorización",
                    ),
                ),
                (
                    "commercial_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor comercial"
                    ),
                ),
                (
                    "realization_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Valor de realización",
                    ),
                ),
                ("appraisal_date", models.DateField(verbose_name="Fecha de tasación")),
                ("appraiser", models.CharField(max_length=150, verbose_name="Tasador")),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "db_table": "properties",
            },
        ),
        migrations.CreateModel(
            name="Mortgage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "secured_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Monto garantizado",
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Primer rango"),
                            (2, "Segundo rango"),
                            (3, "Tercer rango"),
                            (4, "Cuarto rango"),
                        ],
                        default=1,
                        verbose_name="Rango hipotecario",
                    ),
                ),
                (
                    "inscription_status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_TRAMITE", "En trámite"),
                            ("OBSERVADA", "Observada"),
                            ("INSCRITA", "Inscrita"),
                            ("LEVANTADA", "Levantada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                        verbose_name="Estado de inscripción",
                    ),
                ),
                (
                    "registry_seat",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Asiento registral"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortgages",
                        to="core.operation",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mortgages",
                        to="core.property",
                    ),
                ),
            ],
            options={
                "db_table": "mortgages",
            },
        ),
        migrations.CreateModel(
            name="Trust",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "fiduciary_entity",
                    models.CharField(max_length=150, verbose_name="Entidad fiduciaria"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=60,
                        unique=True,
                        verbose_name="Número o código del fideicomiso",
                    ),
                ),
                (
                    "constitution_date",
                    models.DateField(verbose_name="Fecha de constitución"),
                ),
                (
                    "trust_estate",
                    models.CharField(
                        max_length=200, verbose_name="Patrimonio fideicometido"
                    ),
                ),
                (
                    "settlor",
                    models.CharField(max_length=200, verbose_name="Fideicomitente"),
                ),
                (
                    "trustee",
                    models.CharField(max_length=200, verbose_name="Fiduciario"),
                ),
                (
                    "beneficiary",
                    models.CharField(
                        max_length=250, verbose_name="Fideicomisario / beneficiario"
                    ),
                ),
                (
                    "contributed_assets",
                    models.TextField(verbose_name="Bienes aportados"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_CONSTITUCION", "En constitución"),
                            ("PENDIENTE_INSCRIPCION", "Pendiente de inscripción"),
                            ("VIGENTE", "Vigente"),
                            ("EN_EJECUCION", "En ejecución"),
                            ("LIQUIDADO", "Liquidado"),
                            ("EXTINGUIDO", "Extinguido"),
                        ],
                        default="EN_CONSTITUCION",
                        max_length=22,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de vigencia"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de vencimiento"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operations",
                    models.ManyToManyField(
                        blank=True,
                        db_table="trust_operations",
                        related_name="trusts",
                        to="core.operation",
                        verbose_name="Operaciones",
                    ),
                ),
            ],
            options={
                "db_table": "trusts",
                "ordering": ["-constitution_date"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CONTRATO", "Contrato"),
                            ("TASACION", "Tasación"),
                            ("COPIA_LITERAL", "Copia literal"),
                            ("CERT_REGISTRAL", "Certificado registral"),
                            ("SUNARP", "Documento SUNARP"),
                            ("CONTRATO_FIDEICOMISO", "Contrato de fideicomiso"),
                            ("COMPROBANTE", "Comprobante"),
                            ("VOUCHER", "Voucher"),
                            ("ADENDA", "Adenda"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=22,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.document_path, verbose_name="Archivo"
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField()),
                ("is_void", models.BooleanField(default=False)),
                ("void_reason", models.CharField(blank=True, max_length=250)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.client",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.investor",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.operation",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.payment",
                    ),
                ),
                (
                    "trust",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="core.trust",
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="paymentschedule",
            constraint=models.UniqueConstraint(
                fields=("operation", "version", "number"), name="uniq_schedule_row"
            ),
        ),
    ]
