# Generated by Django 5.2.18 on 2026-10-06 22:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="external_ref",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=250,
                null=True,
                unique=True,
                verbose_name="Referencia externa",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="nominal_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Valor nominal por bono",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="series",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Emisión / serie"
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="source",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Registro manual"),
                    ("IMPORT", "Importado de Excel"),
                ],
                default="MANUAL",
                editable=False,
                max_length=8,
                verbose_name="Origen",
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="units",
            field=models.PositiveIntegerField(
                default=1,
                help_text="El interés se redondea por bono.",
                verbose_name="Cantidad de bonos",
            ),
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Etiqueta original (p. ej. PREPAGO).",
                max_length=20,
                verbose_name="Periodo",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="income_tax_withholding",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("4.99"),
                help_text="Se aplica sobre intereses e IMC en la distribución a bonistas.",
                max_digits=5,
                verbose_name="Retención de IR a bonistas (%)",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_rate_pen",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Interés compensatorio/moratorio máximo publicado por el BCRP. Se usa en penalidades tipo IMC.",
                max_digits=8,
                verbose_name="Tasa máxima BCRP soles (% anual)",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="max_rate_usd",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                max_digits=8,
                verbose_name="Tasa máxima BCRP dólares (% anual)",
            ),
        ),
        migrations.AddField(
            model_name="trust",
            name="admin_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Se suma al total a pagar del cronograma consolidado.",
                max_digits=12,
                verbose_name="Comisión administrativa por periodo",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("DNI", "DNI"),
                    ("CE", "Carné de extranjería"),
                    ("RUC", "RUC"),
                    ("PAS", "Pasaporte"),
                    ("SD", "Pendiente de registrar"),
                ],
                default="DNI",
                max_length=3,
                verbose_name="Tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="financialprofile",
            name="penalty_type",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin penalidad"),
                    ("FIXED", "Monto fijo por cuota vencida"),
                    ("PERCENT", "Porcentaje único sobre lo vencido"),
                    ("DAILY_PERCENT", "Porcentaje diario sobre lo vencido"),
                    ("DAILY_FIXED", "Monto fijo por día de atraso"),
                    ("MORATORY", "Tasa moratoria anual (interés simple)"),
                    ("IMC", "IMC: moratorio + compensatorio a tasa máxima (compuesto)"),
                ],
                default="DAILY_PERCENT",
                max_length=14,
                verbose_name="Tipo de penalidad",
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("DNI", "DNI"),
                    ("CE", "Carné de extranjería"),
                    ("RUC", "RUC"),
                    ("PAS", "Pasaporte"),
                    ("SD", "Pendiente de registrar"),
                ],
                default="DNI",
                max_length=3,
                verbose_name="Tipo de documento",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="penalty_type",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin penalidad"),
                    ("FIXED", "Monto fijo por cuota vencida"),
                    ("PERCENT", "Porcentaje único sobre lo vencido"),
                    ("DAILY_PERCENT", "Porcentaje diario sobre lo vencido"),
                    ("DAILY_FIXED", "Monto fijo por día de atraso"),
                    ("MORATORY", "Tasa moratoria anual (interés simple)"),
                    ("IMC", "IMC: moratorio + compensatorio a tasa máxima (compuesto)"),
                ],
                default="NONE",
                max_length=14,
                verbose_name="Tipo de penalidad",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVA", "Activa"),
                    ("AL_DIA", "Al día"),
                    ("POR_VENCER", "Por vencer"),
                    ("VENCIDA", "Vencida"),
                    ("EN_MORA", "En mora crítica"),
                    ("CANCELADA", "Cancelada"),
                    ("REESTRUCTURADA", "Reestructurada"),
                ],
                db_index=True,
                default="ACTIVA",
                max_length=15,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="concept",
            field=models.CharField(
                choices=[
                    ("IMPORTADO", "Importado del Excel"),
                    ("CUOTA", "Pago de cuota"),
                    ("PREPAGO", "Pago adelantado"),
                    ("CANCELACION", "Cancelación total"),
                    ("PENALIDAD", "Pago de penalidad"),
                    ("OTRO", "Otro"),
                ],
                default="CUOTA",
                max_length=12,
                verbose_name="Concepto",
            ),
        ),
        migrations.AlterField(
            model_name="paymentschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("PAGADO", "Pagado"),
                    ("PAGO_PARCIAL", "Pago parcial"),
                    ("VENCIDO", "Vencida"),
                ],
                default="PENDIENTE",
                max_length=12,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="penalty_type",
            field=models.CharField(
                choices=[
                    ("NONE", "Sin penalidad"),
                    ("FIXED", "Monto fijo por cuota vencida"),
                    ("PERCENT", "Porcentaje único sobre lo vencido"),
                    ("DAILY_PERCENT", "Porcentaje diario sobre lo vencido"),
                    ("DAILY_FIXED", "Monto fijo por día de atraso"),
                    ("MORATORY", "Tasa moratoria anual (interés simple)"),
                    ("IMC", "IMC: moratorio + compensatorio a tasa máxima (compuesto)"),
                ],
                max_length=14,
                verbose_name="Tipo de penalidad",
            ),
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Archivo"),
                ),
                ("file", models.FileField(upload_to="importaciones/%Y/%m/")),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "En revisión"),
                            ("CONFIRMED", "Importado"),
                            ("DISCARDED", "Descartado"),
                        ],
                        default="PREVIEW",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("parsed", models.JSONField(default=dict, verbose_name="Datos leídos")),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Resultado"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "import_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="operation",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="core.importbatch",
            ),
        ),
        migrations.CreateModel(
            name="BondHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("units", models.PositiveIntegerField(default=0, verbose_name="Bonos")),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Fracción: 0.777778 = 77.78 %",
                        max_digits=9,
                        verbose_name="Participación",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holdings",
                        to="core.investor",
                        verbose_name="Bonista",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holdings",
                        to="core.operation",
                    ),
                ),
            ],
            options={
                "db_table": "bond_holdings",
                "ordering": ["-percentage"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operation", "investor"), name="uniq_holding"
                    )
                ],
            },
        ),
    ]
